@startuml
hide circle
hide empty members

class Reparatiekaart {
    - klant: Klant 
    - voertuigType: VoertuigType
    - reparatie: ArrayList<String>
    - ontvangstDatum: DateTime
    - tijd: Number 
}

enum VoertuigType <<Enumeration>> {
    Fiets 
    Scooter 
}

class Klant {
    - naam: String
    - telefoonnummer: Number
}
@enduml